// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/easeaico/easeway/internal/views"
	"github.com/easeaico/easeway/internal/views/layout"
)

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"signin-section auth-section\"><div class=\"curve-container\"><div class=\"curve-top\"></div><div class=\"curve-bottom\"></div></div><!--//curve-container--><div class=\"container\"><div class=\"single-col-max mx-auto over-curve px-5\"><div class=\"site-logo mb-4 text-center\"><a class=\"navbar-brand\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL = views.RenderSafeURL("")
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var3)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><img class=\"logo-icon me-2\" src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(views.RenderURL("/assets/images/site-logo.svg"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/user/login.templ`, Line: 19, Col: 91}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" alt=\"logo\"></a></div><div class=\"auth-wrapper mx-auto\"><h2 class=\"auth-heading text-center mb-4\">登录你的账号</h2><div class=\"auth-form-container text-start mx-auto\"><form class=\"auth-form signup-form\" hx-post=\"/user/login\" hx-replace-url=\"true\"><div class=\"email mb-3\"><label class=\"sr-only\" for=\"signin-email\">邮箱</label> <input id=\"signin-email\" name=\"signin-email\" type=\"email\" class=\"form-control signin-email\" placeholder=\"邮箱\" required=\"required\"></div><!--//email--><div class=\"password mb-3\"><div class=\"extra mt-2 position-relative\"><div class=\"mb-0\"><label class=\"sr-only\" for=\"signin-password\">验证码</label> <input id=\"signin-verifycode\" name=\"signin-verifycode\" type=\"text\" class=\"form-control signin-password w-75\" placeholder=\"验证码\"></div><div class=\"forgotten-password\"><button type=\"submit\" name=\"signin-action\" value=\"code\" class=\"btn theme-btn mx-auto\">发送</button></div></div></div><div class=\"text-center\"><button type=\"submit\" name=\"signin-action\" value=\"login\" class=\"btn btn-primary btn-submit theme-btn mx-auto\">登录</button></div></form></div><!--//auth-form-container--><div class=\"auth-footer py-5 mt-5 text-center\"></div></div><!--//auth-wrapper--></div><!--//single-col-max--></div><!--//container--></div><!--//signin-section-->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base("登录").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
