// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

type AccountIncome struct {
	ID            interface{}
	UserID        int64
	RechargeType  int64
	RechargeValue int64
	CreatedAt     interface{}
	UpdatedAt     interface{}
	DeletedAt     interface{}
}

type AccountOutcome struct {
	ID        interface{}
	UserID    int64
	ApiKey    int64
	Tokens    int64
	FeeRate   int64
	Cost      int64
	CreatedAt interface{}
	UpdatedAt interface{}
	DeletedAt interface{}
}

type ApiKey struct {
	ID        interface{}
	UserID    int64
	ApiKey    string
	Spend     int64
	Status    int64
	CreatedAt interface{}
	UpdatedAt interface{}
	DeletedAt interface{}
}

type User struct {
	ID         interface{}
	Email      string
	Amount     int64
	LoginToken string
	CreatedAt  interface{}
	UpdatedAt  interface{}
	DeletedAt  interface{}
}
