// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int64
	UserID    int64
	Name      string
	Key       string
	Spend     int32
	Status    int16
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type Income struct {
	ID            int64
	UserID        int64
	RechargeType  int16
	RechargeValue int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type Outcome struct {
	ID               int64
	UserID           int64
	KeyID            int64
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	FeeRate          int32
	Cost             int32
	Rt               int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
}

type User struct {
	ID               int64
	Email            string
	Amount           int32
	VerificationCode string
	VerificationAt   time.Time
	SessionID        pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
}
