// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package store

import (
	"context"
)

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, api_key, spend, status, created_at, updated_at, deleted_at FROM api_keys WHERE api_key = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAPIKey(ctx context.Context, apiKey string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, apiKey)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKey,
		&i.Spend,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
